version: '3'
services:
  registry:
    image: registry
    volumes:
      - registry-data:/var/lib/registry
      - ./config.yaml:/etc/docker/registry/config.yml
      - ./htpasswd:/etc/docker/registry/htpasswd
    networks:
      - registry-ui-net
    restart: always

  ui:
    image: joxit/docker-registry-ui
    environment:
      - REGISTRY_TITLE=cr.tidu.giize.com
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
    depends_on:
      - registry
    networks:
      registry-ui-net:
      shiba:
        aliases:
          - cr
    ports:
      - 3008:80
    restart: always

volumes:
  registry-data:

networks:
  registry-ui-net:
  shiba:
    external: true

