version: '3'

networks:
  tidu1:
    external: true

services:
  plantuml:
    image: plantuml/plantuml-server
    restart: always
    environment:
      - ALLOW_PLANTUML_INCLUDE=true
    networks:
      - tidu1
