version: '3'

networks:
  shiba:
    external: true
  minikube:
    external: true


services:
  haproxy:
    image: haproxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
      - 563:563
      - 127.0.0.1:10000:10000
    networks:
      - shiba
      - minikube
    volumes:
      - ./config:/usr/local/etc/haproxy
      - /home/tidu/.acme.sh:/live:ro
